HMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('room/', include('room.urls')),
    path('staff/', include('staff.urls'))
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.home_view, name='homepage'),
    path('attendance/<str:type>', views.staff_attendance, name='staff-attendance'),
    path('book/<str:type>', views.book, name='book-room'),
    path('checkin/', views.check_in, name='checkin'),
    path('checkout/', views.check_out, name='checkout'),
    path('reservations/', views.reservations, name='reservations'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('inventory/<str:type>', views.inventory, name='inventory'),
    path('create/<str:type>', views.create, name='create'),
    path('room/<str:type>', views.room_management, name='room'),
    path('order/<str:type>', views.order, name='order'),
    path('expenses/<str:type>', views.expenses, name='expenses'),
    path('salary/<str:type>', views.salary, name='salary'),
    path('revenue/<str:type>', views.revenue, name='revenue'),
    path('chat/<str:type>', views.chat, name='chat'),
    path('pcu', views.pcu, name='pcu'),
    path('sm/<str:type>', views.sm, name='sm'),
]

staff/models.py
from django.db import models
from datetime import datetime


class employee(models.Model):
    full_name = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    auth_level = models.FloatField(blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    created = models.DateTimeField(default=datetime.now, blank=True, null=True)
    active = models.IntegerField(default=1, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    department = models.CharField(max_length=250, blank=True, null=True)
    position = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return str(self.pk) + " " + str(self.full_name)


class admin_conversation(models.Model):
    employee = models.ForeignKey(employee,
                                 on_delete=models.CASCADE, blank=True, null=True)
    conversations = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return str(self.employee) + " " + str(self.conversations)


class attendance(models.Model):
    check_in = models.DateTimeField(blank=True, null=True)
    check_out = models.DateTimeField(blank=True, null=True)
    employee = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True,
                                 null=True, related_name='employee_attendance')

    def __str__(self):
        return str(self.employee)


class inventory(models.Model):
    item_name = models.CharField(max_length=100, blank=True, null=True)
    status = models.IntegerField(default=0, blank=True, null=True)
    item_type = models.CharField(default='unknown', max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.item_name)


class inventory_log(models.Model):
    item = models.ForeignKey(inventory, on_delete=models.CASCADE, blank=True, null=True)
    log_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    action_by = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True, null=True)
    log = models.TextField(blank=True, null=True)
    type = models.CharField(default='unknown', max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.item)


class stock(models.Model):
    item = models.ForeignKey(inventory, on_delete=models.CASCADE, blank=True, null=True)
    current = models.IntegerField(blank=True, null=True)
    type = models.IntegerField(default=0, blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    action_by = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.item) + " " + str(self.current)


class expense(models.Model):
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    item = models.CharField(max_length=250, blank=True, null=True)
    amount = models.FloatField(blank=True, null=True)
    message = models.TextField(default='n/a', blank=True, null=True)
    action_by = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.item + " " + str(self.amount)


class revenue(models.Model):
    source = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=100, blank=True, null=True)
    amount = models.FloatField(blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    message = models.TextField(default='n/a', blank=True, null=True)
    action_by = models.ForeignKey(employee, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.source)


class salary(models.Model):
    employee = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True,
                                 null=True, related_name="hotel_employee")
    pay_date = models.DateTimeField(blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    amount = models.FloatField(blank=True, null=True)
    action_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True,
                                  null=True, related_name="admin_employee")

    def __str__(self):
        return str(self.employee)


class department(models.Model):
    department_title = models.CharField(max_length=100, blank=True, null=True)
    department_val = models.FloatField(blank=True, null=True)
    auth_level = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.department_title


class authentication_level(models.Model):
    level_title = models.CharField(max_length=100, blank=True, null=True)
    level_val = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.level_title


class position(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    no_of_staff = models.IntegerField(blank=True, null=True)
    department = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

staff/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import request
from room.models import *
from .models import *
from room.models import room as hotel_room
from django.db.models import Q
from. import  base
from django.conf import settings
from HMS import settings
from django.db import IntegrityError
from django.db.models import Q
from room import base as room_base

N = 6


def is_slice_in_list(new_array, old_array):
    """ used to check if new array is in old array"""
    len_s = len(new_array) #  so we don't recompute length of new on every iteration
    return any(new_array == old_array[i:len_s+i] for i in range(len(old_array) - len_s+1))


def update_context(context, result):
    """
    function is used to update the context with general details from the result variable
    :param dict: view context
    :param result: the returned value from model action
    :return: 
    """

    if not is_slice_in_list(result['messages'], context['messages']):
        context['messages'].extend(result['messages'])

    if 'messages_count' in result:
        context['messages_count'] = result['messages_count']
    else:
        context['messages_count'] = len(result['messages'])

    if 'message_type' in result:
        # context['message_type'] = result['message_type']
        context.update({'message_type': result['message_type']})
    else:
        context.update({'message_type': settings.NEUTRAL})
    # dict.update({
    #     'message_type': result['message_type'],
    # })


def home_view(request):
    context = {'messages': []}
    if not basic_details(request, context):
        return redirect('staff:login')

    context['booked_rooms_count'] = base.hotel_room().get_booked_rooms(only_count=True)['booked_rooms_count']
    context['free_rooms_count'] = base.hotel_room().get(type="strict", only_count=True)['rooms_count']
    context['all_rooms_count'] = base.hotel_room().get(only_count=True)['rooms_count']
    context['reservations_count'] = base.hotel_room().get_reservations(only_count=True)['reservations_count']

    return render(request, 'staff/index.html', context)


def basic_details(request, context):
    if 'admin_id' not in request.session:
        """ if admin is not signed in, """
        return False
    """ will be used to ad basic info that will be need generally to each context"""
    context.update(
        {
            'level': settings.LEVELS,
            'auth_level': request.session['auth_level'],
            'first_dept': str(list(settings.DEPARTMENTS.keys())[0]),
            'user_type': 'staff',
            'positive': settings.POSITIVE,
            'negative': settings.NEGATIVE,
            'neutral': settings.NEUTRAL,
        })
    return True


def book(request, type):
    """
    for booking and checking user in
    """
    context = {'messages': []}
    if not basic_details(request, context):
        return redirect('staff:login')

    if type == 'now':
        if request.method == 'POST':
            result = base.hotel_room().book(request.session['admin_id'], request.POST)
            if result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])

        context['password'] = base.utilities().generate_password(N)
        """ get room information """
        result = base.hotel_room().get(type="strict")
        if result['status'] != settings.NEGATIVE:
            context['rooms'] = result['rooms']

        context['messages_count'] = result['messages_count']

        """ update context based on result """
        update_context(context, result)

        return render(request, 'reception/booking.html', context)

    elif type == 'reserve':
        context['password'] = base.utilities().generate_password(N)
        if 'pb_id' in request.GET:
            context['pb'] = request.GET['pb_id']

            result = base.hotel_room().get_public_reservation_by_id({'pb_id': request.GET['pb_id']})
            if result['status'] != settings.NEGATIVE:
                context['public_booking_object'] = result['public_booking_object']

                """ get room information """
                result = base.hotel_room().get(type="strict", Post={
                    'room_type_title': context['public_booking_object'].room_type
                })

                if result['status'] != settings.NEGATIVE:
                    context['rooms'] = result['rooms']
                else:
                    context['room_type'] = context['public_booking_object'].room_type
                    context['messages'].extend(result['messages'])

            elif result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])

            update_context(context, result)
        else:
            """ get room information """
            result = base.hotel_room().get(type="strict")
            if result['status'] != settings.NEGATIVE:
                context['rooms'] = result['rooms']

        if request.method == 'POST':
            result = base.hotel_room().book(request.session['admin_id'], request.POST)
            if result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])

            update_context(context, result)
        return render(request, 'reception/reservation.html', context)

    elif type == 'take':
        if request.method == 'POST':
            result = base.hotel_room().take_my_reservation(request.session['admin_id'], request.POST)
            if result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])
        return render(request, 'reception/take-reservation.html', context)

    elif type == 'public-reservations':
        result = base.hotel_room().public_reservations()
        if result['status'] != settings.NEGATIVE:
            context['public_booking_object'] = result['public_booking_object']
            context['count'] = result['count']
        else:
            context['messages'].extend(result['messages'])

        update_context(context, result)
        return render(request, 'hms-admin/public_reservations.html', context)
    else:
        return redirect('staff:homepage')


def check_in(request):
    context = {'messages': []}
    if not basic_details(request, context):
        return redirect('staff:login')

    result = base.hotel_room().get_booked_rooms()
    if result['status'] != settings.NEGATIVE:
        context['booking_object'] = result['booking_object']

    update_context(context, result)
    return render(request, 'hms-admin/checkin_list.html', context)


def check_out(request):
    context = {'messages': []}
    if not basic_details(request, context):
        return redirect('staff:login')

    if request.method == 'POST':
        try:
            """
            for checking out customers
            """
            room_object = room.objects.get(room_no=request.POST['room_no'])
            booking_object = booking.objects.filter(~Q(check_in_date=None), room=room_object, check_out_date=None).first()
            if booking_object is not None or booking_object:
                booking_object.check_out_date = datetime.now()
                booking_object.check_out_action_by = employee.objects.get(pk=request.session['admin_id'])

                booking_object.save()

                """after checking out add this room to free rooms """
                result = base.hotel_room().release_room({'room_object': room_object})
                if result['status'] == settings.NEGATIVE:
                    context['messages'].append("Failed to free up room, please contact admin. Room no: " +
                                               request.POST['room_no'] + ".")
                else:
                    context['messages'].append("Checked out " + request.POST['room_no'] + " successfully.")
                    context['message_type'] = settings.POSITIVE
            else:
                raise Exception()
        except Exception as e:
            print(e)
            context['messages'].append("Failed to checkout room " + request.POST['room_no'] + ".")
            context['message_type'] = settings.NEGATIVE

    # result = base.hotel_room().get_booked_rooms()
    # if result['status'] != settings.NEGATIVE:
    #     context['booking_object'] = result['booking_object']

    return render(request, 'reception/checkout.html', context)


def reservations(request):
    context = {'messages': []}
    if not basic_details(request, context):
        return redirect('staff:login')

    result = base.hotel_room().get_reservations()
    if result['status'] != settings.NEGATIVE:
        context['reservations'] = result['reservations']
        context['total'] = result['total']

    update_context(context, result)
    return render(request, 'hms-admin/reservation_list.html', context)


def staff_attendance(request, type):
    context = {'messages': []}

    if not basic_details(request, context):
        return redirect('staff:login')

    attendance_today_url = reverse('staff:staff-attendance'
                               ,current_app=request.resolver_match.namespace,
                               kwargs={'type': 'today'})

    if type == 'in':
        if request.method == 'POST':
            result = base.hotel_admin().attendance_signin(request.POST)
            print(result)
            if result['status'] != settings.NEGATIVE:
                return redirect(attendance_today_url)

            update_context(context, result)
        return render(request, 'staff/attendance_signin.html', context)

    elif type == "today":
        result = base.hotel_admin().get_attendance()
        if result['status'] != settings.NEGATIVE:
            """ if any messages are sent with the result append """
            if result['messages_count'] > 0:
                context['messages'].extend(result['messages'])
            context['attendance_object'] = result['attendance_object']

templates/staff/admin-signin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Gloran Hotel | Admin</title>
  <link rel="shortcut icon" href="static/img/favicon/favicon-32x32.png" type="image/x-icon">
  <link rel="shortcut icon" href="static/img/favicon/favicon-16x16.png" type="image/x-icon">
  <link rel="shortcut icon" href="static/img/favicon/apple-touch-icon.png" type="image/x-icon">
  <link rel="stylesheet" href="static/css/bootstrap.min.css" />
  <link href="static/font/ionicons/css/ionicons.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="static/css/main.min.css" />
</head>

<body>
  <div class="wrapper tm-bg-img">
    <!-- HEADER -->
    <header class="tm-header position-relative tm-shadow-btm">
      <nav class="navbar">
        <a class="navbar-brand" href="index.html">Gloran Hotel</a>
      </nav>
    </header>
    <div class="container-fluid">
      <div class="row py-2">
        <div class="col-12 col-sm-6 col-lg-4 m-auto">
          <div class="tm-box rounded">
            <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
              Sign in
            </h4>
            <div class="tm-box-body">
              <div class="mb-3 text-center">
                <img src="./static/img/user_1.png" alt="user" class="img-fluid rounded tm-user-img-xm">
              </div>
              <form action="#" class="form-horizontal mt-5">
                <div class="form-group">
                  <div class="input-group clearfix">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="icon ion-ios-at"></i>
                      </div>
                    </div>
                    <label for="userEmail" class="sr-only">Email</label>
                    <input type="email" class="form-control" name="userEmail" id="userEmail" placeholder="Email">
                  </div>
                </div>
                <div class="form-group">
                  <div class="input-group clearfix">
                    <div class="input-group-prepend">
                      <div class="input-group-text">
                        <i class="icon ion-ios-key"></i>
                      </div>
                    </div>
                    <label for="userPass" class="sr-only">Password</label>
                    <input type="password" name="userPass" id="userPass" class="form-control" placeholder="Password">
                  </div>
                </div>
                <div class="form-group text-center mt-2">
                  <button type="submit" class="btn btn-primary">Login</button>
                </div>
              </form>
              <p class="text-center">Forgot password? <a href="signup.html" class="link">Change</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="./static/js/jquery-3.3.1.min.js"></script>
  <script src="./static/js/bootstrap.bundle.min.js"></script>
  <script src="./static/js/main.js"></script>
</body>

</html>

templates/staff/attendance.html
{% extends 'staff/base.html' %}
{% block container %}
  <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Attendance</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'staff:staff-attendance' 'in' %}">Sign in</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{% url 'staff:staff-attendance' 'out' %}">Sign out</a></li>
          </ol>
        </nav>
      </div>
      <div class="card-body p-0">
              <div class="table-responsive flex-fill">
                <table class="table table-hover m-0">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">S/N</th>
                      <th scope="col">Name <small>(click to view)</small></th>
                      <th scope="col">Sign in</th>
                      <th scope="col">Sign out</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for object in attendance_object %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="#">{{ object.employee.full_name }}</a></td>
                        <td>{{ object.check_in }}</td>
                        <td> {% if object.check_out %}
                                {{ object.check_out }}
                              {% else %}
                                  --------
                              {% endif %}
                        </td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            <div class="card-footer pb-0">
              <nav class="page navigation">
                <ul class="pagination justify-content-end">
                  <li class="page-item"><a href="#" class="page-link" aria-label="previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a></li>
                  <li class="page-item active"><a href="#" class="page-link">1 <span class="sr-only">(current)</span></a></li>
                  <li class="page-item"><a href="#" class="page-link">2</a></li>
                  <li class="page-item"><a href="#" class="page-link">3</a></li>
                  <li class="page-item"><a href="#" class="page-link" aria-label="next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Next</span>
                    </a></li>
                </ul>
              </nav>
            </div>

    </main>
{% endblock %}

templates/staff/attendance_signin.html
{% extends 'staff/base.html' %}
{% block container %}
    <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="card-body p-0">
        <div class="table-responsive flex-fill">
          <div class="container-fluid">
            <div class="row py-2">
              <div class="col-12 col-sm-6 col-lg-4 m-auto">
                <div class="tm-box rounded">
                  <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
                    Attendance
                  </h4>
                  <div class="tm-box-body">
                    <div class="mb-3 text-center">
                      <img src="/static/img/user_1.png" alt="user" class="img-fluid rounded tm-user-img-xm">
                    </div>
                    <form action="" method="post" class="form-horizontal mt-5">
                      {% csrf_token %}
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-at"></i>
                            </div>
                          </div>
                          <label for="userEmail" class="sr-only">Email</label>
                          <input type="email" class="form-control" name="email" id="userEmail" placeholder="Email">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-key"></i>
                            </div>
                          </div>
                          <label for="userPass" class="sr-only">Password</label>
                          <input type="password" name="password" id="userPass" class="form-control" placeholder="Password">
                        </div>
                      </div>
                      <div class="form-group text-center mt-2">
                        <button type="submit" class="btn btn-primary">Sign in</button>
                      </div>
                    </form>
                    <p class="text-center">Have a nice time</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

templates/staff/attendance_signout.html
{% extends 'staff/base.html' %}
{% block container %}
  <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="card-body p-0">
        <div class="table-responsive flex-fill">
          <div class="container-fluid">
            <div class="row py-2">
              <div class="col-12 col-sm-6 col-lg-4 m-auto">
                <div class="tm-box rounded">
                  <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
                    Attendance
                  </h4>
                  <div class="tm-box-body">
                    <div class="mb-3 text-center">
                      <img src="/static/img/user_1.png" alt="user" class="img-fluid rounded tm-user-img-xm">
                    </div>
                    <form action="" method="post" class="form-horizontal mt-5">
                      {% csrf_token %}
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-at"></i>
                            </div>
                          </div>
                          <label for="userEmail" class="sr-only">Email</label>
                          <input type="email" class="form-control" name="email" id="userEmail" placeholder="Email">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-key"></i>
                            </div>
                          </div>
                          <label for="userPass" class="sr-only">Password</label>
                          <input type="password" name="password" id="userPass" class="form-control" placeholder="Password">
                        </div>
                      </div>
                      <div class="form-group text-center mt-2">
                        <button type="submit" class="btn btn-primary">Sign out</button>
                      </div>
                    </form>
                    <p class="text-center">Have a nice time</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    </main>
{% endblock %}

templates/staff/index.html
{% extends 'staff/base.html' %}
{% load static %}
{% block title %}
  {% if auth_level == settings.Admin.val %}
    Gloran Hotel | Admin
  {% elif auth_level == settings.Receptionist.val %}
  	Gloran Hotel | Reception
  {% else %}
  	Gloran Hotel | Unknown
  {% endif %}
{% endblock %}

{% block container %}
  <!-- MAIN CONTENT -->
  <main class="px-3 tm-content">
    <div class="row">
      <div class="page-title mr-auto px-3 pt-2">
        <h4 class="h3">Dashboard</h4>
      </div>
      <nav aria-label="breadcrumb" class="ml-auto tm-breads">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'staff:homepage' %}">Home</a></li>
          <li class="breadcrumb-item" aria-current="page"><a href="{% url 'staff:homepage' %}">Dashboard</a></li>
        </ol>
      </nav>
    </div>
    <div class="card-deck mt-4 mb-3">
        <div class="card tm-shadow-out">
          <div class="p-0 clearfix">
            <div class="bg-gold py-1 py-sm-4 px-2 col-12 col-lg-4 float-left text-center">
              <i class="icon ion-ios-help-buoy tm-f3 text-white"></i>
            </div>
            <div class="col-12 col-lg-8 px-3 py-3 float-left">
              <h6 class="mb-2">Total No of Rooms</h6>
              <h5 class="m-0">{{ all_rooms_count }}</h5>
              <a href="{% url 'staff:room' 'view' %}" class="btn btn-primary">View all</a>
            </div>
          </div>
        </div>
        <div class="card tm-shadow-out">
          <div class="p-0 clearfix">
            <div class="bg-gold py-1 py-sm-4 px-2 col-12 col-lg-4 float-left text-center">
              <i class="icon ion-ios-help-buoy tm-f3 text-white"></i>
            </div>
            <div class="col-12 col-lg-8 px-3 py-3 float-left">
              <h6 class="mb-2">Total Free Rooms</h6>
              <h5 class="m-0">{{ free_rooms_count }}</h5>
              <a href="{% url 'staff:room' 'view' %}?strict" class="btn btn-primary">View all</a>
            </div>
          </div>
        </div>            
        <div class="card tm-shadow-out">
          <div class="p-0 clearfix">
            <div class="bg-gold py-1 py-sm-4 px-2 col-12 col-lg-4 float-left text-center">
              <i class="icon ion-ios-notifications tm-f3 text-white"></i>
            </div>
            <div class="col-12 col-lg-8 px-3 py-3 float-left">
              <h6 class="mb-2">Total Occupied Rooms</h6>
              <h5 class="m-0">{{ booked_rooms_count }}</h5>
              <a href="{% url 'staff:checkin' %}" class="btn btn-primary">View all</a>
            </div>
          </div>
        </div>

        <div class="card tm-shadow-out">
          <div class="p-0 clearfix">
            <div class="bg-gold py-1 py-sm-4 px-2 col-12 col-lg-4 float-left text-center">
              <i class="icon ion-ios-notifications tm-f3 text-white"></i>
            </div>
            <div class="col-12 col-lg-8 px-3 py-3 float-left">
              <h6 class="mb-2">Total Reservations</h6>
              <h5 class="m-0">{{ reservations_count }}</h5>
              <a href="" class="btn btn-primary">View all</a>
            </div>
          </div>
        </div>

    </div>
    
  </main>

{% endblock %}