HMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('room/', include('room.urls')),
    path('staff/', include('staff.urls'))
]

room/urls.py
from django.urls import path
from . import views
app_name = 'room'
urlpatterns = [
    path('', views.room_index_view, name='room'),
    path('chat/<str:type>', views.room_chat, name='chat'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

room/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class room_type(models.Model):
    type = models.CharField(max_length=25, blank=True, null=True)
    no_of_rooms = models.IntegerField(default=0, blank=True, null=True)
    free_rooms = models.IntegerField(default=0, blank=True, null=True)
    price = models.FloatField(default=0, blank=True, null=True)
    discount = models.FloatField(default=0, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    action_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE,
                                  blank=True, null=True, related_name='room_type_action_by')

    def __str__(self):
        return self.type


class room_type_service(models.Model):
    file_name = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    active = models.IntegerField(default=1, blank=True, null=True)
    created_by = models.ForeignKey('staff.employee',
                                   on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    room_type = models.ForeignKey(room_type, on_delete=models.CASCADE,
                                  blank=True, null=True, related_name="room_type_service")

    def __str__(self):
        return str(self.room_type) + " " + str(self.title)


class room(models.Model):
    room_no = models.CharField(max_length=10, blank=True, null=True, unique=True)
    reserved = models.IntegerField(default=0, blank=True, null=True)
    status = models.IntegerField(default=1, blank=True, null=True)
    type = models.ForeignKey(room_type,
                             on_delete=models.CASCADE, blank=True, null=True, related_name='room_type')

    def __str__(self):
        return str(self.room_no) + " " + str(self.type)


class room_image(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE,
                             blank=True, null=True, related_name="room_image")
    file_name = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True, null=True)
    created_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE,
                                   blank=True, null=True, related_name="image_created_by_admin")
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.file_name)


class room_log(models.Model):
    room = models.ForeignKey(room,
                             on_delete=models.CASCADE, blank=True, null=True, related_name='log_for_room_no')
    action_by = models.ForeignKey('staff.employee',
                                  on_delete=models.CASCADE, blank=True, null=True, related_name='employee')
    log_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    log = models.TextField(blank=True, null=True)


class review(models.Model):
    review_content = models.TextField(blank=True, null=True)
    user = models.ForeignKey('user_information', on_delete=models.CASCADE,
                             blank=True, null=True, related_name='user_review')
    review_date = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(default=0, blank=True, null=True)
    booking = models.ForeignKey('booking', on_delete=models.CASCADE, blank=True, null=True,
                                related_name='review_for_booking')

    def __str__(self):
        return str(self.review_content)


class user_information(models.Model):
    full_name = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(blank=True, null=True, unique=True)
    phone = models.CharField(max_length=20, blank=True, null=True, unique=True)
    count = models.IntegerField(default=1, blank=True, null=True)
    next_of_kin_name = models.CharField(max_length=250, blank=True, null=True)
    next_of_kin_phone = models.CharField(max_length=250, blank=True, null=True)
    source = models.CharField(max_length=250, default="staff", blank=True, null=True)

    def __str__(self):
        return str(self.email)


class booking(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE, blank=True, null=True, related_name='room_booking')
    check_in_date = models.DateTimeField(blank=True, null=True)
    check_out_date = models.DateTimeField(blank=True, null=True)
    reservation_date = models.DateTimeField(blank=True, null=True)
    proposed_check_out_date = models.DateTimeField(blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    user = models.ForeignKey('user_information', on_delete=models.CASCADE, blank=True, null=True,
                             related_name='user_info')
    price = models.FloatField(blank=True, null=True)
    discount = models.FloatField(blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    action_by = models.ForeignKey('staff.employee',  on_delete=models.CASCADE, blank=True, null=True,
                                  related_name='booked_by')
    check_out_action_by = models.ForeignKey('staff.employee',  on_delete=models.CASCADE, blank=True, null=True,
                                            related_name='checkout_by')
    reserve_action_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True, null=True,
                                          related_name='reserved_by')

    def __str__(self):
        return str(self.pk) + " " + str(self.room.room_no) + \
               " " + " (" + str(self.check_in_date) + "-" + str(self.check_out_date) + ")"


class order(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE, blank=True, null=True)
    item = models.CharField(max_length=250, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    quantity = models.IntegerField(default=1, blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return str(self.item)


class message(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE,
                             blank=True, null=True, related_name="room_message")
    booking = models.ForeignKey(booking, on_delete=models.CASCADE,
                                blank=True, null=True, related_name="booking_message")
    employee = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True, null=True)
    sent_by = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return str(self.booking)

room/views.py
from django.shortcuts import render, redirect
from django.http import request
from .models import *
from . import base
import hashlib
from django.db.models import Q
from django.conf import settings
from HMS import settings
from django.urls import reverse

app_name = 'room'
PASSWORD_SALT = '$.2@7!29^Bc;a)f2:144f6$@_)5196b01.%6.FdD04dA0%'


def hash(content):
    return hashlib.md5(
        PASSWORD_SALT.encode() + (hashlib.sha1(content.encode()).hexdigest()).encode()).hexdigest()


def is_slice_in_list(new_array, old_array):
    """ used to check if new array is in old array"""
    len_s = len(new_array) #  so we don't recompute length of new on every iteration
    return any(new_array == old_array[i:len_s+i] for i in range(len(old_array) - len_s+1))


def update_context(context, result):
    """
    function is used to update the context with general details from the result variable
    :param dict: view context
    :param result: the returned value from model action
    :return:
    """
    if not is_slice_in_list(result['messages'], context['messages']):
        context['messages'].extend(result['messages'])
    if 'messages_count' in result:
        context['messages_count'] = result['messages_count']
    else:
        context['messages_count'] = len(result['messages'])
    if 'message_type' in result:
        context.update({
            'message_type': result['message_type'],
        })
    else:
        context.update({
            'message_type': settings.NEUTRAL,
        })


def basic_details(request, context):
    if 'booking_id' not in request.session:
        """ if admin is not signed in, """
        return False
    """ will be used to ad basic info that will be need by each context"""
    context.update({'room_no': request.session['room_no'], 'booking': request.session['booking_id'], 'user_type': 'room'})
    return True


def room_index_view(request):
    context = {'messages': []}
    if not basic_details(request, context):

        return redirect('room:login')
    result = base.room_base().get_booking_info({'booking_id': request.session['booking_id']})

    if result['status'] != settings.NEGATIVE:
        context['booking_object'] = result['booking_object']

    update_context(context, result)
    return render(request, "room/index.html", context)


def login(request):
    context = {'messages': []}

    action = False

    # if request.method == 'GET':
    #     if 'login' in request.GET:
    #         result = base.room_base().login(request.GET)
    #         action = True
    if request.method == 'POST':
        result = base.room_base().login(request.POST)
        action = True

    if action:
        if result['status'] == settings.NEGATIVE:
            update_context(context, result)

        elif result['status'] != settings.NEGATIVE:
            request.session['booking_id'] = result['booking_object'].pk
            request.session['room_no'] = result['booking_object'].room.room_no
            request.session['full_name'] = result['booking_object'].user.full_name
            request.session['check_in_date'] = str(result['booking_object'].check_in_date)
            return redirect('room:room')

        else:
            context['messages'].append("An error occurred.")
    return render(request, 'room/signin.html',  context)


def logout(request):
    if 'booking_id' in request.session:
        del request.session['booking_id']
        del request.session['room_no']
        del request.session['full_name']
        del request.session['check_in_date']

    return redirect('room:room')


def room_chat(request, type):
    context = {'messages': [], 'base_page': 'room/base.html'}
    if not basic_details(request, context):

        return redirect('room:login')

    if type == "send":
        action = False
        # if request.method == 'GET':
        #     result = base.chat().send(request.GET)
        #     action = True
        if request.method == 'POST':
            result = base.chat().send(request.POST)
            action = True

        if action:
            if result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])
        room_url = reverse('room:chat',
                           current_app=request.resolver_match.namespace,
                           kwargs={'type': 'fetch'})
        return redirect(room_url)
    elif type == "fetch":
        result = base.chat().get_messages({'booking': request.session['booking_id'], 'user_type': context['user_type']})

        if result['status'] == settings.NEGATIVE:
             context['messages'].extend(result['messages'])
        else:
            context['chat_messages'] = result['chat_messages']
        context['booking'] = int(request.session['booking_id'])
        context['url'] = reverse('room:chat'
                               ,current_app=request.resolver_match.namespace,
                               kwargs={'type': 'send'})
        return render(request, "room/message.html", context)

templates/room/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>{% block title %}Gloran Hotel | Rooms {% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link href="{% static 'font/ionicons/css/ionicons.min.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/main.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/message.css' %}" />
</head>

<body>
  <div class="wrapper">
    <!-- HEADER -->
    <header class="tm-header tm-shadow-btm">
      <nav class="navbar justify-content-between justify-content-sm-start">
        <div class="d-none d-sm-block d-md-none tm-semi-close-nav" id="tm-semi-close-nav">
          <i class="icon ion-ios-arrow-round-back tm-f4 text-white"></i>
        </div>
        <a class="navbar-brand" href="{% url 'room:room' %}">Gloran Hotel</a>
        <button type="button" class="btn btn-primary navbar-toggler border-0 d-sm-none ml-4" data-toggle="collapse"
          data-target="#sidebarNav" aria-expanded="false" aria-controls="sidebarNav" aria-label="Toggle sidebar nav">
          <i class="icon ion-ios-menu tm-f4"></i>
        </button>
      </nav>
    </header>
    <div class="container-fluid tm-main-con">
      <div class="flex-sm-nowrap">
        <!-- SIDEBAR -->
        <aside class="px-1 tm-sidebar border-sm-right text-truncate">
          <div class="py-2 pt-sm-4 d-none d-sm-flex flex-nowrap justify-content-end justify-content-sm-start align-items-center">
            <div class="tm-title text-uppercase px-2">Menu</div>
          </div>
          <nav class="collapse d-sm-block tm-nav-links py-2 px-0" id="sidebarNav">
            <ul class="nav flex-column">
              <li class="nav-item ">
                <a href="{% url 'room:room' %}" class="nav-link clearfix">
                  <span class="float-left">
                    <span class="badge mr-2 tm-sidebar-icon"><i class="icon ion-ios-home"></i></span>
                    <span class="align-text-bottom">Dashboard</span>
                  </span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'room:chat' 'fetch' %}" class="nav-link clearfix">
                  <span class="float-left">
                    <span class="badge mr-2 tm-sidebar-icon"><i class="icon ion-ios-people"></i></span>
                    <span class="align-text-bottom">Chat</span>
                  </span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'room:logout' %}" class="nav-link clearfix">
                  <span class="float-left">
                    <span class="badge mr-2 tm-sidebar-icon"><i class="icon ion-ios-people"></i></span>
                    <span class="align-text-bottom">Logout</span>
                  </span>
                </a>
              </li>
            </ul>
          </nav>
        </aside>

        <!-- MAIN CONTENT -->
        {% block container %} {% endblock %}
        
      </div>
    </div>

    <!-- FOOTER -->
    <div class="tm-footer tm-shadow bg-white text-center clearfix">
      <div class="offset-sm-4 offset-md-3 offset-xl-2">
        &copy; Copyright 2019
      </div>
    </div>
  </div>
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/room/checkout.html
{% extends 'room/base.html' %}
{% load static %}


{% block container %}

<main class="px-3 tm-content">
  <div class="row">
    <div class="page-title mr-auto px-3 pt-2">
      <h4 class="h3">Check-out</h4>
    </div>
    <nav aria-label="breadcrumb" class="ml-auto tm-breads">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="checkout.html"> Check-out</a></li>
      </ol>
    </nav>
  </div>
  <div class="row pt-1 pb-3 pt-sm-2 pb-sm-4">
    <div class="col-12">
      <div class="card tm-shadow-btm">
        <div class="card-header d-flex flex-wrap flex-md-nowrap justify-content-between align-items-center">
          Check out Rooms
          
        </div>
        <div class="card-body p-5">
          <form class="mt-3 mt-md-0 clearfix">
            <div class="input-group mb-0 col-10 col-sm-10 px-0 px-sm-2 ml-auto">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <i class="icon ion-ios-search"></i>
                </div>
              </div>
              <input type="search" name="search-rooms" id="search-rooms" class="form-control" placeholder="Room Number..."
                aria-describedby="search-patient" />
              <div class="input-group-prepend text-center">
                <button type="submit" class="btn btn-primary">Check-out</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/room/index.html
{% extends 'room/base.html' %}
{% load static %}


{% block container %}

<main class="px-3 tm-content">
  <div class="card-body p-0">
    <div class="table-responsive flex-fill">
      <div class="container-fluid">
        <div class="row py-2">
          <div class="col-12 col-sm-10 col-lg-8 m-auto">
            <div class="tm-box rounded">
              <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
                Dashboard
              </h4>
              <div class="tm-box-body">
                <div class="table-responsive flex-fill">
                  <table class="table table-hover m-0">
                    <tbody>
                      <tr>
                        <th scope="row" class="text-primary">Name</th>
                        <td>
                            <a>
                                {% if booking_object.user %}
                                  {{ booking_object.user.full_name }}
                                {% else %}
                                  ----
                                {% endif%}
                            </a>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row" class="text-primary">Room No.</th>
                        <td>
                            <a>
                                {% if booking_object.room %}
                                  {{ booking_object.room.room_no }}
                                {% else %}
                                  ----
                                {% endif%}
                            </a>
                        </td>
                      </tr>
                      <tr>
                        <th scope="row" class="text-primary">Room Type</th>
                        <td>
                            <a>
                                {% if booking_object.room.type %}
                                  {{ booking_object.room.type.type }}
                                {% else %}
                                  ----
                                {% endif%}
                            </a>
                        </td>
                      </tr>
                      <!--<tr>-->
                        <!--<th scope="row" class="text-primary">Admin Phone</th>-->
                        <!--<td><a>08041991185</a></td>-->
                      <!--</tr>-->
                      <tr>
                        <th scope="row" class="text-primary">Check in Date</th>
                        <td>
                            <a>
                                {% if booking_object.check_in_date %}
                                  {{ booking_object.check_in_date|date:"d/M/Y" }}
                                {% else %}
                                  ----
                                {% endif%}
                            </a>
                        </td>
                      </tr>                        
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/room/login.html
{% extends 'room/base.html' %}
{% load static %}

{% block container %}
    <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="card-body p-0">
        <div class="table-responsive flex-fill">
          <div class="container-fluid">
            <div class="row py-2">
              <div class="col-12 col-sm-6 col-lg-4 m-auto">
                <div class="tm-box rounded">
                  <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
                    Login
                  </h4>

                  {% if messages %}
                      <div class="alert {% if message_type == negative %}alert-danger{% elif message_type == positive %}alert-success{%endif%} alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                          <span class="sr-only">Close</span>
                        </button>
                        {% for child in messages %}
                          <strong>{{ child }}</strong>
                        {% endfor %}
                      </div>
                  {% endif %}

                  <div class="tm-box-body">
                    <div class="mb-3 text-center">
                      <img src="/static/img/user_1.png" alt="user" class="img-fluid rounded tm-user-img-xm">
                    </div>
                    <form action="" method="post" class="form-horizontal mt-5">
                      {% csrf_token %}
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-at"></i>
                            </div>
                          </div>
                          <label for="room_no" class="sr-only">room_no</label>
                          <input type="text" class="form-control" name="room_no" id="room_no" placeholder="Room No">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-key"></i>
                            </div>
                          </div>
                          <label for="userPass" class="sr-only">Password</label>
                          <input type="password" name="password" id="userPass" class="form-control" placeholder="Password">
                        </div>
                      </div>
                      <div class="form-group text-center mt-2">
                        <button type="submit" class="btn btn-primary">Sign in</button>
                      </div>
                    </form>
                    <p class="text-center">Have a nice time</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

templates/room/message.html
{% extends base_page %}

{% load static %}

{% if base_page == 'staff/base.html' %}
    {%block extra_css %}<link rel="stylesheet" href="/static/css/message.css" />{% endblock %}
{% endif %}
{% block container %}
<main class="px-3 tm-content">
  <div class="row">
    <div class="page-title mr-auto px-3 pt-2">
      <h4 class="h3">Chat Section</h4>
    </div>
    <nav aria-label="breadcrumb" class="ml-auto tm-breads">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'room:room' %}">Home</a></li>
      </ol>
    </nav>
  </div>
  <div class="row pt-1 pb-3 pt-sm-2 pb-sm-4">
    <div class="col-12">
      <div class="card tm-shadow-btm">
        <div class="card-header d-flex flex-wrap flex-md-nowrap justify-content-between align-items-center">
          Chat
          
        </div>
        <div class="chat d-flex justify-content-center">
          <div class="card card-container">
            <div class="card-body msg_card_body">
                {% for child in chat_messages %}
                    {% if child.sent_by == booking or child.sent_by == admin_id %}
                        <div class="d-flex justify-content-end mb-4">
                          <div class="">
                            <div class="msg_cotainer_send">
                              {{ child.message.message }}
                            </div>
                            <span class="msg_time_send">{{ child.time }}</span>
                          </div>
                        </div>
                    {% else %}
                        <div class="d-flex justify-content-start mb-4">
                          <div class="">
                            <div class="msg_cotainer">
                              {{ child.message.message }}
                            </div>
                            <span class="msg_time">{{ child.time }}</span>
                          </div>
                        </div>
                    {% endif %}
                {% endfor %}

            </div>
            <div class="card-footer">
              <form action="{{ url }}" method="post">
                {% csrf_token %}
                <div class="input-group">
                  <input type="hidden" value="{{booking}}" name="booking"/>
                  <input type="hidden" value="{{ user_type }}" name="user_type"/>
                  <input type="hidden" value="{{room_no}}" name="room_no">
                  {% if admin_id %}
                      <input type="hidden" value="{{admin_id}}" name="employee">
                  {% endif %}
                  <textarea name="message" class="form-control type_msg" placeholder="Type your message..."></textarea>
                  <div class="input-group-append">
                    <button type="submit" class="btn send_btn">Send</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/room/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>{% block title %}Gloran Hotel | Rooms {% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/favicon/favicon.ico' %}" type="image/x-icon">
  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link href="{% static 'font/ionicons/css/ionicons.min.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/main.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/message.css' %}" />
</head>

<body>
  <div class="wrapper tm-bg-img">
    <!-- HEADER -->
    <header class="tm-header position-relative tm-shadow-btm">
      <nav class="navbar">
        <a class="navbar-brand" href="index.html">Gloran Hotel</a>
      </nav>
    </header>
    <div class="container-fluid">
      <div class="row py-2">
        <div class="col-12 col-sm-6 col-lg-4 m-auto">
          <div class="tm-box rounded">
            <h4 class="tm-box-header text-center text-capitalize text-gray border-bottom mb-4 pb-3 tm-black-50">
              Login
            </h4>

            {% if messages %}
                <div class="alert {% if message_type == negative %}alert-danger{% elif message_type == positive %}alert-success{%endif%} alert-dismissible fade show" role="alert">
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                  </button>
                  {% for child in messages %}
                    <strong>{{ child }}</strong>
                  {% endfor %}
                </div>
            {% endif %}
                  
            <div class="tm-box-body">
                    <div class="mb-3 text-center">
                      <img src="/static/img/user_1.png" alt="user" class="img-fluid rounded tm-user-img-xm">
                    </div>
                    <form action="" method="post" class="form-horizontal mt-5">
                      {% csrf_token %}
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-at"></i>
                            </div>
                          </div>
                          <label for="room_no" class="sr-only">room_no</label>
                          <input type="text" class="form-control" name="room_no" id="room_no" placeholder="Room No">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="input-group clearfix">
                          <div class="input-group-prepend">
                            <div class="input-group-text">
                              <i class="icon ion-ios-key"></i>
                            </div>
                          </div>
                          <label for="userPass" class="sr-only">Password</label>
                          <input type="password" name="password" id="userPass" class="form-control" placeholder="Password">
                        </div>
                      </div>
                      <div class="form-group text-center mt-2">
                        <button type="submit" class="btn btn-primary">Sign in</button>
                      </div>
                    </form>
                    <p class="text-center">Have a nice time</p>
                  </div>
                </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="./static/js/jquery-3.3.1.min.js"></script>
  <script src="./static/js/bootstrap.bundle.min.js"></script>
  <script src="./static/js/main.js"></script>
</body>

</html>