HMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('room/', include('room.urls')),
    path('staff/', include('staff.urls'))
]

room/urls.py
from django.urls import path
from . import views
app_name = 'room'
urlpatterns = [
    path('', views.room_index_view, name='room'),
    path('chat/<str:type>', views.room_chat, name='chat'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('', views.home_view, name='homepage'),
    path('attendance/<str:type>', views.staff_attendance, name='staff-attendance'),
    path('book/<str:type>', views.book, name='book-room'),
    path('checkin/', views.check_in, name='checkin'),
    path('checkout/', views.check_out, name='checkout'),
    path('reservations/', views.reservations, name='reservations'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('inventory/<str:type>', views.inventory, name='inventory'),
    path('create/<str:type>', views.create, name='create'),
    path('room/<str:type>', views.room_management, name='room'),
    path('order/<str:type>', views.order, name='order'),
    path('expenses/<str:type>', views.expenses, name='expenses'),
    path('salary/<str:type>', views.salary, name='salary'),
    path('revenue/<str:type>', views.revenue, name='revenue'),
    path('chat/<str:type>', views.chat, name='chat'),
    path('pcu', views.pcu, name='pcu'),
    path('sm/<str:type>', views.sm, name='sm'),
]

room/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class room_type(models.Model):
    type = models.CharField(max_length=25, blank=True, null=True)
    no_of_rooms = models.IntegerField(default=0, blank=True, null=True)
    free_rooms = models.IntegerField(default=0, blank=True, null=True)
    price = models.FloatField(default=0, blank=True, null=True)
    discount = models.FloatField(default=0, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    action_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE,
                                  blank=True, null=True, related_name='room_type_action_by')

    def __str__(self):
        return self.type


class room_type_service(models.Model):
    file_name = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    active = models.IntegerField(default=1, blank=True, null=True)
    created_by = models.ForeignKey('staff.employee',
                                   on_delete=models.CASCADE, blank=True, null=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    room_type = models.ForeignKey(room_type, on_delete=models.CASCADE,
                                  blank=True, null=True, related_name="room_type_service")

    def __str__(self):
        return str(self.room_type) + " " + str(self.title)


class room(models.Model):
    room_no = models.CharField(max_length=10, blank=True, null=True, unique=True)
    reserved = models.IntegerField(default=0, blank=True, null=True)
    status = models.IntegerField(default=1, blank=True, null=True)
    type = models.ForeignKey(room_type,
                             on_delete=models.CASCADE, blank=True, null=True, related_name='room_type')

    def __str__(self):
        return str(self.room_no) + " " + str(self.type)


class room_image(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE,
                             blank=True, null=True, related_name="room_image")
    file_name = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(default=datetime.now, blank=True, null=True)
    created_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE,
                                   blank=True, null=True, related_name="image_created_by_admin")
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.file_name)


class room_log(models.Model):
    room = models.ForeignKey(room,
                             on_delete=models.CASCADE, blank=True, null=True, related_name='log_for_room_no')
    action_by = models.ForeignKey('staff.employee',
                                  on_delete=models.CASCADE, blank=True, null=True, related_name='employee')
    log_date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    log = models.TextField(blank=True, null=True)


class review(models.Model):
    review_content = models.TextField(blank=True, null=True)
    user = models.ForeignKey('user_information', on_delete=models.CASCADE,
                             blank=True, null=True, related_name='user_review')
    review_date = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(default=0, blank=True, null=True)
    booking = models.ForeignKey('booking', on_delete=models.CASCADE, blank=True, null=True,
                                related_name='review_for_booking')

    def __str__(self):
        return str(self.review_content)


class user_information(models.Model):
    full_name = models.CharField(max_length=250, blank=True, null=True)
    email = models.EmailField(blank=True, null=True, unique=True)
    phone = models.CharField(max_length=20, blank=True, null=True, unique=True)
    count = models.IntegerField(default=1, blank=True, null=True)
    next_of_kin_name = models.CharField(max_length=250, blank=True, null=True)
    next_of_kin_phone = models.CharField(max_length=250, blank=True, null=True)
    source = models.CharField(max_length=250, default="staff", blank=True, null=True)

    def __str__(self):
        return str(self.email)


class booking(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE, blank=True, null=True, related_name='room_booking')
    check_in_date = models.DateTimeField(blank=True, null=True)
    check_out_date = models.DateTimeField(blank=True, null=True)
    reservation_date = models.DateTimeField(blank=True, null=True)
    proposed_check_out_date = models.DateTimeField(blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)
    user = models.ForeignKey('user_information', on_delete=models.CASCADE, blank=True, null=True,
                             related_name='user_info')
    price = models.FloatField(blank=True, null=True)
    discount = models.FloatField(blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    action_by = models.ForeignKey('staff.employee',  on_delete=models.CASCADE, blank=True, null=True,
                                  related_name='booked_by')
    check_out_action_by = models.ForeignKey('staff.employee',  on_delete=models.CASCADE, blank=True, null=True,
                                            related_name='checkout_by')
    reserve_action_by = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True, null=True,
                                          related_name='reserved_by')

    def __str__(self):
        return str(self.pk) + " " + str(self.room.room_no) + \
               " " + " (" + str(self.check_in_date) + "-" + str(self.check_out_date) + ")"


class order(models.Model):
    booking = models.ForeignKey(booking, on_delete=models.CASCADE, blank=True, null=True)
    item = models.CharField(max_length=250, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    quantity = models.IntegerField(default=1, blank=True, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return str(self.item)


class message(models.Model):
    room = models.ForeignKey(room, on_delete=models.CASCADE,
                             blank=True, null=True, related_name="room_message")
    booking = models.ForeignKey(booking, on_delete=models.CASCADE,
                                blank=True, null=True, related_name="booking_message")
    employee = models.ForeignKey('staff.employee', on_delete=models.CASCADE, blank=True, null=True)
    message = models.TextField(blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(default=datetime.now, blank=True, null=True)
    sent_by = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return str(self.booking)

room/views.py
from django.shortcuts import render, redirect
from django.http import request
from .models import *
from . import base
import hashlib
from django.db.models import Q
from django.conf import settings
from HMS import settings
from django.urls import reverse

app_name = 'room'
PASSWORD_SALT = '$.2@7!29^Bc;a)f2:144f6$@_)5196b01.%6.FdD04dA0%'


def hash(content):
    return hashlib.md5(
        PASSWORD_SALT.encode() + (hashlib.sha1(content.encode()).hexdigest()).encode()).hexdigest()


def is_slice_in_list(new_array, old_array):
    """ used to check if new array is in old array"""
    len_s = len(new_array) #  so we don't recompute length of new on every iteration
    return any(new_array == old_array[i:len_s+i] for i in range(len(old_array) - len_s+1))


def update_context(context, result):
    """
    function is used to update the context with general details from the result variable
    :param dict: view context
    :param result: the returned value from model action
    :return:
    """
    if not is_slice_in_list(result['messages'], context['messages']):
        context['messages'].extend(result['messages'])
    if 'messages_count' in result:
        context['messages_count'] = result['messages_count']
    else:
        context['messages_count'] = len(result['messages'])
    if 'message_type' in result:
        context.update({
            'message_type': result['message_type'],
        })
    else:
        context.update({
            'message_type': settings.NEUTRAL,
        })


def basic_details(request, context):
    if 'booking_id' not in request.session:
        """ if admin is not signed in, """
        return False
    """ will be used to ad basic info that will be need by each context"""
    context.update({'room_no': request.session['room_no'], 'booking': request.session['booking_id'], 'user_type': 'room'})
    return True


def room_index_view(request):
    context = {'messages': []}
    if not basic_details(request, context):

        return redirect('room:login')
    result = base.room_base().get_booking_info({'booking_id': request.session['booking_id']})

    if result['status'] != settings.NEGATIVE:
        context['booking_object'] = result['booking_object']

    update_context(context, result)
    return render(request, "room/index.html", context)


def login(request):
    context = {'messages': []}

    action = False

    # if request.method == 'GET':
    #     if 'login' in request.GET:
    #         result = base.room_base().login(request.GET)
    #         action = True
    if request.method == 'POST':
        result = base.room_base().login(request.POST)
        action = True

    if action:
        if result['status'] == settings.NEGATIVE:
            update_context(context, result)

        elif result['status'] != settings.NEGATIVE:
            request.session['booking_id'] = result['booking_object'].pk
            request.session['room_no'] = result['booking_object'].room.room_no
            request.session['full_name'] = result['booking_object'].user.full_name
            request.session['check_in_date'] = str(result['booking_object'].check_in_date)
            return redirect('room:room')

        else:
            context['messages'].append("An error occurred.")
    return render(request, 'room/signin.html',  context)


def logout(request):
    if 'booking_id' in request.session:
        del request.session['booking_id']
        del request.session['room_no']
        del request.session['full_name']
        del request.session['check_in_date']

    return redirect('room:room')


def room_chat(request, type):
    context = {'messages': [], 'base_page': 'room/base.html'}
    if not basic_details(request, context):

        return redirect('room:login')

    if type == "send":
        action = False
        # if request.method == 'GET':
        #     result = base.chat().send(request.GET)
        #     action = True
        if request.method == 'POST':
            result = base.chat().send(request.POST)
            action = True

        if action:
            if result['status'] == settings.NEGATIVE:
                context['messages'].extend(result['messages'])
        room_url = reverse('room:chat',
                           current_app=request.resolver_match.namespace,
                           kwargs={'type': 'fetch'})
        return redirect(room_url)
    elif type == "fetch":
        result = base.chat().get_messages({'booking': request.session['booking_id'], 'user_type': context['user_type']})

        if result['status'] == settings.NEGATIVE:
             context['messages'].extend(result['messages'])
        else:
            context['chat_messages'] = result['chat_messages']
        context['booking'] = int(request.session['booking_id'])
        context['url'] = reverse('room:chat'
                               ,current_app=request.resolver_match.namespace,
                               kwargs={'type': 'send'})
        return render(request, "room/message.html", context)

templates/hms-admin/add_inventory.html
{% extends 'staff/base.html' %}
{% block container %}
<!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Dashboard</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="{% url 'staff:inventory' 'add' %}">Add Inventory</a></li>
          </ol>
        </nav>
      </div>
      <div class="row pt-1 pb-3 pt-sm-2 pb-sm-4">
        <div class="col-12">
          <div class="card tm-shadow-btm">
            <div class="card-header d-flex flex-wrap flex-md-nowrap justify-content-between align-items-center">
              Add a new Item
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="row">
                  <form action="" method="post" class="form-horizontal col-12 col-md-10 col-lg-7">
                    {% csrf_token %}
                    <div class="form-group form-row">
                      <label for="expenses" class="col-12 col-sm-3 col-form-label">Item</label>
                      <input type="text" placeholder="Item Name" name="item_name" id="expenses" class="form-control col-12 col-sm-9" required>
                    </div>

                    <div class="form-group form-row">
                      <label for="type" class="col-12 col-sm-3 col-form-label">Item Type</label>
                      <input type="text" placeholder="Item Type" name="item_type" id="type" class="form-control col-12 col-sm-9" required>
                    </div>

                    <div class="form-group form-row">
                      <label for="quantity" class="col-12 col-sm-3 col-form-label">Quantity</label>
                      <input type="number" step="1" placeholder="Quantity" name="quantity" id="quantity" class="form-control col-12 col-sm-9" required>
                    </div>

                    <div class="form-group text-right">
                      <button type="submit" class="btn btn-primary">Save</button>
                    </div>

                  </form>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

    </main>
{% endblock %}

templates/hms-admin/add_staff.html
{% extends 'staff/base.html' %}
{% block container %}
<!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Dashboard</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item" aria-current="page"><a href="index.html">Dashboard</a></li>
          </ol>
        </nav>
      </div>
      <div class="row pt-1 pb-3 pt-sm-2 pb-sm-4">
        <div class="col-12">
          <div class="card tm-shadow-btm">
            <div class="card-header d-flex flex-wrap flex-md-nowrap justify-content-between align-items-center">
              Add a new Staff
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="row">
                  <form action="#" method="post" class="form-horizontal col-12 col-md-10 col-lg-7">
                    {% csrf_token %}
                    <div class="form-group form-row">
                      <label for="full_name" class="col-12 col-sm-3 col-form-label">Full name</label>
                      <input type="text" placeholder="Full name" name="full_name" id="full_name" class="form-control col-12 col-sm-9">
                    </div>
                    <div class="form-group form-row">
                      <label for="email" class="col-12 col-sm-3 col-form-label">E-mail</label>
                      <input type="email" placeholder="E-mail" name="email" id="email" class="form-control col-12 col-sm-9">
                    </div>

                    <div class="form-group form-row">
                      <label for="department" class="col-12 col-sm-3 col-form-label">Department</label>
                      <select name="department" id="department">
                        {% for dept,value in departments.items %}
                            <option value="{{dept}}">{{value.name}}</option>
                        {% endfor %}
                      </select>
                    </div>

                    <div class="form-group form-row">
                      <label for="position" class="col-12 col-sm-3 col-form-label">Position</label>
                      <select name="position" id="position">
                        {% for position,value in positions.items %}
                            <option value="{{position}}">{{position}}</option>
                        {% endfor %}
                      </select>
                    </div>

                    <div class="form-group form-row">
                      <label for="phone" class="col-12 col-sm-3 col-form-label">Phone</label>
                      <input type="tel" placeholder="Phone number" name="phone" id="phone" class="form-control col-12 col-sm-9">
                    </div>

                    <div class="form-group form-row">
                      <label for="password" class="col-12 col-sm-3 col-form-label">Password</label>
                      <input type="password"  name="password" id="password" class="form-control col-12 col-sm-9">
                    </div>
                    <div class="form-group form-row">
                      <label for="employed_date" class="col-12 col-sm-3 col-form-label">Employed Date</label>
                      <input type="date" name="employed_on" id="employed_date" class="form-control col-12 col-sm-9">
                    </div>
                    <div class="form-group form-row">
                      <label for="employee_address" class="col-12 col-sm-3 col-form-label">Address</label>
                      <input type="text" placeholder="Address" name="address" id="employee_address" class="form-control col-12 col-sm-9">
                    </div>
                    <div class="form-group text-right">
                      <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                  </form>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

    </main>
{% endblock %}

{% block extra_script %}
<script>
  /**var position = document.getElementById('position')
  var department = document.getElementById('department')

  var departments = {}

  function load_department_info()
  {
      {% for dept, value in departments.items %}
          var positions = []
          {% for position,value in departments.items %}

          {% endfor %}
          departments[{{dept}}] =
              {
                  'name': {{dept}},
                  ''
              }
      {% endfor %}
  }

  department.onchange = function()
  {

  }**/

</script>
{% endblock%}

templates/hms-admin/inventory.html
{% extends 'staff/base.html' %}
{% block container %}
<!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Inventory</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'staff:homepage' %}">Home</a></li>
          </ol>
        </nav>
      </div>
      <div class="card-deck mt-4 mb-3">
          <div class="table-responsive flex-fill">
                <table class="table table-hover m-0">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">S/N</th>
                      <th scope="col">Item Name</th>
                      <th scope="col">Item Type</th>
                      <th scope="col">Current Stock</th>
                      <th scope="col">Date</th>
                      <th scope="col">Admin</th>
                    </tr>
                  </thead>
                  <tbody>
                      {% for child in inventory_object %}

                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>
                                {% if child.inventory.item_name %}
                                    {{child.inventory.item_name}}
                                {% else%}
                                    ----
                                {% endif %}
                            </td>
                            <td>

                                {% if child.inventory.item_type %}
                                    {{child.inventory.item_type}}
                                {% else %}
                                    ----
                                {% endif %}
                            </td>
                            <td>
                                {% if child.stock.current %}
                                    {{child.stock.current}}
                                {% else %}
                                    ----
                                {% endif %}
                            </td>
                            <td>
                                {% if child.stock.date %}
                                    {{child.stock.date}}
                                {% else %}
                                    ----
                                {% endif %}
                            </td>
                            <td>
                                {% if child.stock.action_by.email %}
                                    {{child.stock.action_by.email}}
                                {% else %}
                                    ----
                                {% endif %}

                            </td>
                        </tr>
                      {% endfor %}
                  </tbody>
                </table>
          </div>
      </div>

    </main>
{% endblock %}

templates/hms-admin/pcu.html
{% extends 'staff/base.html' %}
{% block container %}
    <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Contact Us Form Inputs</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="add_room.html">Total: {{count}}</a></li>
          </ol>
        </nav>
      </div>
      <div class="card-body p-0">
              <div class="table-responsive flex-fill">
                <table class="table table-hover m-0">
                  <thead class="thead-light">
                    <tr>
                        <th scope="col">S/N</th>
                        <th scope="col">Name</th>
                        <th scope="col">E=mail</th>
                        <th scope="col">Message</th>
                        <th scope="col">Handled</th>
                    </tr>
                  </thead>
                  <tbody>
                      {%  for child in public_contact_object %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>
                                {{ child.contact.full_name }}
                            </td>
                            <td>
                                {% if child.contact.email %}
                                    {{ child.contact.email }}
                                {% else %}
                                  -------
                                {% endif%}
                            </td>
                            <td>
                                {% if child.contact.content %}
                                    {{ child.contact.content }}
                                {% else %}
                                  ------
                                {% endif%}
                            </td>
                            <td>
                                <a href="{% url 'staff:pcu' %}?pcu_id={{ child.contact.pk }}">Done</a>
                            </td>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            <div class="card-footer pb-0">
              <nav class="page navigation">
                <ul class="pagination justify-content-end">
                  <li class="page-item"><a href="#" class="page-link" aria-label="previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a></li>
                  <li class="page-item active"><a href="#" class="page-link">1 <span class="sr-only">(current)</span></a></li>
                  <li class="page-item"><a href="#" class="page-link">2</a></li>
                  <li class="page-item"><a href="#" class="page-link">3</a></li>
                  <li class="page-item"><a href="#" class="page-link" aria-label="next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Next</span>
                    </a></li>
                </ul>
              </nav>
            </div>
    </main>
{% endblock %}
{% block extra_script %}

{% endblock %}

templates/hms-admin/public_reservations.html
{% extends 'staff/base.html' %}
{% block container %}
    <!-- MAIN CONTENT -->
    <main class="px-3 tm-content">
      <div class="row">
        <div class="page-title mr-auto px-3 pt-2">
          <h4 class="h3">Reservations</h4>
        </div>
        <nav aria-label="breadcrumb" class="ml-auto tm-breads">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="add_room.html">Total: {{count}}</a></li>
          </ol>
        </nav>
      </div>
      <div class="card-body p-0">
              <div class="table-responsive flex-fill">
                <table class="table table-hover m-0">
                  <thead class="thead-light">
                    <tr>
                        <th scope="col">S/N</th>
                        <th scope="col">Client</th>
                        <th scope="col">Room type</th>
                        <th scope="col">Check-in</th>
                        <th scope="col">Check-out</th>
                    </tr>
                  </thead>
                  <tbody>
                      {%  for child in public_booking_object %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td><a href="{% url 'staff:book-room' 'reserve' %}?pb_id={{child.booking.pk}}">{{ child.booking.user.full_name }}</a></td>
                            <td>
                                {{ child.booking.room_type }}
                            </td>
                            <td>
                                {% if child.booking.proposed_check_in_date %}
                                  {{child.booking.proposed_check_in_date|date:"b d, Y"}}
                                {% else %}
                                  -------
                                {% endif%}
                            </td>
                            <td>
                                {% if child.booking.proposed_check_out_date %}
                                  {{child.booking.proposed_check_out_date|date:"b d, Y"}}
                                {% else %}
                                  ------
                                {% endif%}
                            </td>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>

            <div class="card-footer pb-0">
              <nav class="page navigation">
                <ul class="pagination justify-content-end">
                  <li class="page-item"><a href="#" class="page-link" aria-label="previous">
                      <span aria-hidden="true">&laquo;</span>
                      <span class="sr-only">Previous</span>
                    </a></li>
                  <li class="page-item active"><a href="#" class="page-link">1 <span class="sr-only">(current)</span></a></li>
                  <li class="page-item"><a href="#" class="page-link">2</a></li>
                  <li class="page-item"><a href="#" class="page-link">3</a></li>
                  <li class="page-item"><a href="#" class="page-link" aria-label="next">
                      <span aria-hidden="true">&raquo;</span>
                      <span class="sr-only">Next</span>
                    </a></li>
                </ul>
              </nav>
            </div>
    </main>
{% endblock %}
{% block extra_script %}

{% endblock %}